### ISSUE TITLE
[Feature Request] Implement Sort Title for Games

### ISSUE THREAD

**Issue by kesslerboy81** [Misunderstood-Wookiee/RetroPassEX#26]
**Proposal**
In Launchbox we are able to sort games by their titles, making it much cleaner for game series to be in the correct order (E.G. Secret of Monkey Island, Monkey Island 2 and Curse of Monkey Island can be put together simply by renaming the Sort title as Monkey Island 1, Monkey Island 2, Monkey Island 3 etc). At the moment the games are only sorted alphabetically within Launchpass.

RetroPass literally just added this to their last release so we know it's possible.

Thanks and keep up the good work.

**Comment by Misunderstood-Wookiee** [comment]
We took that exact change over from retropass before release are you 💯 it's not working as we didn't test that bit as it had no conflict between our code and the code of retropass.

**Comment by Misunderstood-Wookiee** [comment]
Have been working on a [HotFix](https://github.com/Misunderstood-Wookiee/LaunchPass/tree/PlatfromDisplayOrder_HotFix) for this, among other standing issues.  Expect a release in the coming days.

**As you can see Game Title Sort by # appears to be working**  
![LaunchBox](https://user-images.githubusercontent.com/22002023/235391020-b09ed0a4-d494-4af9-a21e-2d1b9a23e5bb.png)
![LP](https://user-images.githubusercontent.com/22002023/235391030-74054319-1293-459a-a907-a787fe8b5f8c.png)

**Comment by kesslerboy81** [comment]
Okay cool. Looking forward to it. Sorry just seen previous message. Definitely wasn’t working when I tested it.Keep up the great work.On 1 May 2023, at 03:05, MoistDreams ***@***.***> wrote:﻿
I believe the latest build being worked on may have resolved this issue for you.

**Comment by Misunderstood-Wookiee** [comment]
Should be resolved as of #27 
Try the new release, and if have any future problems, let us know :)
