### ISSUE TITLE
[Bug] LanchPass crashs

### ISSUE THREAD

**Issue by wellingtonssilva-leishman** [Misunderstood-Wookiee/RetroPassEX#30]
I have the files from Launhbox on external drive, Retropass loads and show everything, follow the SortOrder and start everything ok.
But, when I try to start Launchpass, it reads only the first 4 collections, then stops.
Sometimes it shows more collection, but when I go to details, it crashs and closes.

Most of my collections have in average 100 games, I have 25 collections.

Attached are my platform files from LaunchBox
[Platforms.zip](https://github.com/Misunderstood-Wookiee/LaunchPass/files/11443372/Platforms.zip)

**Comment by danprice142** [comment]
@wellingtonssilva-leishman do you have the latest version installed and did you delete the old version before installing the new one? I also recommend restarting your Xbox after deleting any app/game before installing another version as the Xbox sometimes leaves old files behind does cause problems! Also if you are updating from the previous build it might be worth deleting the LaunchPass.xml and the LaunchPass folder with its contents from the USB drive just in case

**Comment by Misunderstood-Wookiee** [comment]
Following on from Dan's response, 

A blurb from our troubleshooting section of the guide was recently added after I personally troubleshot my own crashes related to collections displaying. 

`A potential crash exists when there are a large number of systems with huge collections above 2000 in any given playlist/platform collection, it is recommended that for collections above 1500, you split them up into playlists with appropriate names (example: Gameboy 1, Gameboy 2). This specifically applies to total titles while displaying the full collection of that platform/playlist. `

Please Note this blurb pertains to total titles within a single collection, not total titles across all platforms, It has relatively no impact on the Platform/Playlist screen, it affects trying to show the entire contents of a platform. 

 **more precisely**
-  4000+ Titles = an immediate freeze followed by app exit. 
-  3500+ Titles = ^ the same
-  2500 Titles = stuttery pop-in of box arts and potentially a crash but not always.
-  < 2300 Titles = Reliably Smooth
- < 2000 Titles = Optimal Speed and Stability.

**However, may be un-related to this issue but added here for the sake of troubleshooting.**

**Comment by wellingtonssilva-leishman** [comment]
@danprice142 , yes I have the latest version installed, I never installed it before.

**Comment by wellingtonssilva-leishman** [comment]
@Misunderstood-Wookiee my full collection has 6164 Titles.
Top 3 are:
GBA - 1038
SNES - 804
NES - 786

So, I would say from your table, if the values are by collection, the my biggest one has half of 2k and should have optimal speed and stability.

I can provide you more info if necessary and you think would help.
I know on console I can see the log, but am I able to export it to a file and send it to you?
Or maybe any other file from Lanchbox.

Thank you.

**Comment by Misunderstood-Wookiee** [comment]
On console you can use dev portal on Web browser and there is a capture
image button  to dump a screenshot 😉.

How many collections? I have 24 total platforms currently and well over 10k
titles across all.

Your numbers are well under what I've tested to cause issues for me.
I'll formulate s better response later

I'd honeslty try set usb permissions and re install launchpass removing any
old data from it, also what are you running for storage what is the speed
capability?

Best Regards,
Geoffrey Hughes

**Comment by wellingtonssilva-leishman** [comment]
@Misunderstood-Wookiee this is my device (image attached)

![image](https://github.com/Misunderstood-Wookiee/LaunchPass/assets/49085156/0483c5e7-82fb-41bc-8763-c2d19ec11d56)

**Comment by wellingtonssilva-leishman** [comment]
It seems to specific platforms files (from LaunchBox) are failing, and making it close.
Just to be clear, the same platform files works well on Retropass.
I think, maybe some special character or something like this is preventing it to load. But I was not able to identify which one.

I removed all the platfotm files, then I put one XBOX360 for example, it loads well, show the covers, etc.
Then I removed the XBOX360 platform file and added the NintendoDS one, with small collection, and it fails to load.
I did the same test adding the Nintendo GW collection, it fail in the same way.
The 3 files are attached:
XBOX360 - Working
[Platforms.zip](https://github.com/Misunderstood-Wookiee/LaunchPass/files/11510930/Platforms.zip)

DS and GW - Not working

**Comment by Misunderstood-Wookiee** [comment]
> It seems to specific platforms files (from LaunchBox) are failing, and making it close. Just to be clear, the same platform files works well on Retropass. I think, maybe some special character or something like this is preventing it to load. But I was not able to identify which one.
> 
> I removed all the platfotm files, then I put one XBOX360 for example, it loads well, show the covers, etc. Then I removed the XBOX360 platform file and added the NintendoDS one, with small collection, and it fails to load. I did the same test adding the Nintendo GW collection, it fail in the same way. The 3 files are attached: XBOX360 - Working [Platforms.zip](https://github.com/Misunderstood-Wookiee/LaunchPass/files/11510930/Platforms.zip)
> 
> DS and GW - Not working

**Xbox 360**
`<ApplicationPath>F:\roms\xbox360\Games\4D5707E9 - Mortal Kombat vs DC Universe - UNCUT\Mortal Kombat vs DC Universe - UNCUT.xex</ApplicationPath>`

Both your other two Game Watch & DS are using a different game path
`<ApplicationPath>E:\roms\gameandwatch\Hippo Teeth.mgw</ApplicationPath>`
`<ApplicationPath>E:\roms\nds\Need for Speed - Underground 2.nds</ApplicationPath>`}

How are these imported? 
Launchpass does not support multiple USB devices.
It is recommended when importing roms/games that they are kept on the same USB as LaunchPass/LaunchBox 
and when importing choose to use files in their current location, below is how I have my USB setup.

![image](https://github.com/Misunderstood-Wookiee/LaunchPass/assets/22002023/a15af76a-a02b-44d7-b98c-34a799e5e44e)
![image](https://github.com/Misunderstood-Wookiee/LaunchPass/assets/22002023/15dfbbc4-62f0-4f92-8d76-48ab9c041c1e)
![image](https://github.com/Misunderstood-Wookiee/LaunchPass/assets/22002023/2c967db7-f977-48cd-bbee-d993b2ed5187)

If you must you can choose to copy games to your launchbox games location which will put them in your launchbox/games and create sub folders for platforms etc on the device that launchbox is running/installed on, useful if you did not already have them copied onto the USB somewhere, in my case I have a Games folder already setup with all the platforms and roms sorted into them.

**Comment by wellingtonssilva-leishman** [comment]
@Misunderstood-Wookiee , yes I use 2 external drivers. As games from xbox360 for example take too much space with the DLCs, I splited XBOX360, PS2, Gamecube and Wii Games on F: and all the others collections on E:, where Launchbox is (E:\Laucnhbox). 

Ok, I understand when you say it should not work, but as it is a fork from Retropass, I tought it would work in the same way. If I go to  Retropass, it works wicth all collection on 2 external drivers.

For example, if I use the XBOX360 (already attached) collection on F: and SNK Collection (Attached now) on E:, the Launchpass works. even with 2 different external drives. 
So the question is, Why does it work with a limited amount of collections in 2 ext drivers? 
Maybe the limitation is X amount of games on each drive, not 2 ext drivers itself.

Thanks,



[Arcade - SNK Neo Geo.zip](https://github.com/Misunderstood-Wookiee/LaunchPass/files/11524840/Arcade.-.SNK.Neo.Geo.zip)

**Comment by Misunderstood-Wookiee** [comment]
Retropass developer added the multi storage option after we developed
launchpass and we had only attempted to bring it across once so far and
couldn't get it to work right, so for now we still use the single storage
only which tbh we don't think is a problem.

So the issue then is you're trying to load collections across disks and we
don't have that supported yet.

Best Regards,
Geoffrey Hughes

**Comment by danprice142** [comment]
It is a Fork of RetroPass but we started working on this way before that feature got added to RetroPass, LaunchPass and RetroPass should be considered different apps as they are both being actively developed but with different features and are going in directions

**Comment by wellingtonssilva-leishman** [comment]
Maybe this could be a new feature for future releases.

Thanks for the answers.
