### ISSUE TITLE
Add Duckstation to the App.

### ISSUE THREAD

**Issue by kSHOU98** [Misunderstood-Wookiee/RetroPassEX#42]
Add Duckstation to LaunchPass, the emulator is very good. Swanstation is fine but I prefer Duckstation.

Is possible to add Duckstation to LaunchPass? Or you need some permission from the Duckstation Dev?

**Comment by danprice142** [comment]
Swanstation is a Fork of Duckstation it is maintained unlike Duckstation and is the best option for Xbox, Duckstation won’t get support unless it is updated or a new Port is made

**Comment by JJRoyale** [comment]
Closing correctly the issue by closing as not planned (even if it was already closed)
