### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by eradzh87** [Misunderstood-Wookiee/RetroPassEX#45]
**Proposal**

**Describe alternatives you've considered**

**Additional context**

**Comment by JJRoyale** [comment]
uh, i think you should say the proposal and the features

**Comment by Misunderstood-Wookiee** [comment]
If this still looks like this when I wake up tomorrow I am closing this.

**Comment by JJRoyale** [comment]
Closing this as there is no explanation of the issue.
